import { Component, Output, EventEmitter, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import * as i0 from "@angular/core";
import * as i1 from "@angular/router";
const _forTrack0 = ($index, $item) => $item.id;
function NavbarComponent_Conditional_11_Template(rf, ctx) { if (rf & 1) {
    i0.ɵɵelementStart(0, "span", 10);
    i0.ɵɵtext(1);
    i0.ɵɵelementEnd();
} if (rf & 2) {
    const ctx_r0 = i0.ɵɵnextContext();
    i0.ɵɵadvance();
    i0.ɵɵtextInterpolate1(" ", ctx_r0.unreadCount, " ");
} }
function NavbarComponent_Conditional_12_Conditional_4_Template(rf, ctx) { if (rf & 1) {
    const _r2 = i0.ɵɵgetCurrentView();
    i0.ɵɵelementStart(0, "button", 27);
    i0.ɵɵlistener("click", function NavbarComponent_Conditional_12_Conditional_4_Template_button_click_0_listener() { i0.ɵɵrestoreView(_r2); const ctx_r0 = i0.ɵɵnextContext(2); return i0.ɵɵresetView(ctx_r0.markAllAsRead()); });
    i0.ɵɵtext(1, "Mark as read");
    i0.ɵɵelementEnd();
} }
function NavbarComponent_Conditional_12_For_7_Template(rf, ctx) { if (rf & 1) {
    i0.ɵɵelementStart(0, "div", 28)(1, "p", 29);
    i0.ɵɵtext(2);
    i0.ɵɵelementEnd();
    i0.ɵɵelementStart(3, "small", 30);
    i0.ɵɵelement(4, "i", 31);
    i0.ɵɵtext(5);
    i0.ɵɵelementEnd()();
} if (rf & 2) {
    const n_r3 = ctx.$implicit;
    i0.ɵɵclassProp("bg-light", n_r3.unread);
    i0.ɵɵadvance();
    i0.ɵɵclassProp("text-dark", n_r3.unread)("text-muted", !n_r3.unread);
    i0.ɵɵadvance();
    i0.ɵɵtextInterpolate(n_r3.text);
    i0.ɵɵadvance(3);
    i0.ɵɵtextInterpolate(n_r3.time);
} }
function NavbarComponent_Conditional_12_Template(rf, ctx) { if (rf & 1) {
    i0.ɵɵelementStart(0, "div", 11)(1, "div", 20)(2, "span", 21);
    i0.ɵɵtext(3, "Notifications");
    i0.ɵɵelementEnd();
    i0.ɵɵconditionalCreate(4, NavbarComponent_Conditional_12_Conditional_4_Template, 2, 0, "button", 22);
    i0.ɵɵelementEnd();
    i0.ɵɵelementStart(5, "div", 23);
    i0.ɵɵrepeaterCreate(6, NavbarComponent_Conditional_12_For_7_Template, 6, 8, "div", 24, _forTrack0);
    i0.ɵɵelementEnd();
    i0.ɵɵelementStart(8, "div", 25)(9, "a", 26);
    i0.ɵɵtext(10, "View All Notifications");
    i0.ɵɵelementEnd()()();
} if (rf & 2) {
    const ctx_r0 = i0.ɵɵnextContext();
    i0.ɵɵadvance(4);
    i0.ɵɵconditional(ctx_r0.unreadCount > 0 ? 4 : -1);
    i0.ɵɵadvance(2);
    i0.ɵɵrepeater(ctx_r0.notifications);
} }
function NavbarComponent_Conditional_23_Template(rf, ctx) { if (rf & 1) {
    const _r4 = i0.ɵɵgetCurrentView();
    i0.ɵɵelementStart(0, "div", 19)(1, "div", 32)(2, "div", 21);
    i0.ɵɵtext(3);
    i0.ɵɵelementEnd();
    i0.ɵɵelementStart(4, "small", 33);
    i0.ɵɵtext(5);
    i0.ɵɵelementEnd()();
    i0.ɵɵelementStart(6, "a", 34);
    i0.ɵɵelement(7, "i", 35);
    i0.ɵɵtext(8, " My Profile ");
    i0.ɵɵelementEnd();
    i0.ɵɵelementStart(9, "a", 36);
    i0.ɵɵelement(10, "i", 37);
    i0.ɵɵtext(11, " Settings ");
    i0.ɵɵelementEnd();
    i0.ɵɵelement(12, "hr", 38);
    i0.ɵɵelementStart(13, "button", 39);
    i0.ɵɵlistener("click", function NavbarComponent_Conditional_23_Template_button_click_13_listener() { i0.ɵɵrestoreView(_r4); const ctx_r0 = i0.ɵɵnextContext(); return i0.ɵɵresetView(ctx_r0.logout()); });
    i0.ɵɵelement(14, "i", 40);
    i0.ɵɵtext(15, " Logout ");
    i0.ɵɵelementEnd()();
} if (rf & 2) {
    let tmp_1_0;
    let tmp_2_0;
    const ctx_r0 = i0.ɵɵnextContext();
    i0.ɵɵadvance(3);
    i0.ɵɵtextInterpolate((tmp_1_0 = ctx_r0.authService.currentUser()) == null ? null : tmp_1_0.name);
    i0.ɵɵadvance(2);
    i0.ɵɵtextInterpolate((tmp_2_0 = ctx_r0.authService.currentUser()) == null ? null : tmp_2_0.email);
} }
export class NavbarComponent {
    authService = inject(AuthService);
    toggleSidebar = new EventEmitter();
    showNotifications = false;
    showProfileMenu = false;
    // Mock notifications list
    notifications = [
        { id: 1, text: 'New issue reported at Vanguard Heights: Leakage detected', time: '10m ago', unread: true },
        { id: 2, text: 'Cement material request approved for Vance Concrete', time: '1h ago', unread: true },
        { id: 3, text: 'Weekly progress report generated by Shradha S', time: '4h ago', unread: false }
    ];
    get unreadCount() {
        return this.notifications.filter(n => n.unread).length;
    }
    get userRoleLabel() {
        const role = this.authService.userRole();
        if (!role)
            return '';
        return role.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
    }
    toggleNotify() {
        this.showNotifications = !this.showNotifications;
        this.showProfileMenu = false;
    }
    toggleProfile() {
        this.showProfileMenu = !this.showProfileMenu;
        this.showNotifications = false;
    }
    markAllAsRead() {
        this.notifications.forEach(n => n.unread = false);
    }
    logout() {
        this.authService.logout();
    }
    static ɵfac = function NavbarComponent_Factory(__ngFactoryType__) { return new (__ngFactoryType__ || NavbarComponent)(); };
    static ɵcmp = /*@__PURE__*/ i0.ɵɵdefineComponent({ type: NavbarComponent, selectors: [["app-navbar"]], outputs: { toggleSidebar: "toggleSidebar" }, decls: 24, vars: 10, consts: [[1, "navbar", "navbar-expand-lg", "fixed-top", "shadow-sm", "px-4", "bg-white", "border-bottom"], [1, "container-fluid", "p-0", "d-flex", "justify-content-between", "align-items-center"], [1, "d-flex", "align-items-center", "gap-3"], ["id", "sidebarToggleBtn", "title", "Toggle Sidebar", 1, "btn", "btn-light", "d-flex", "align-items-center", "justify-content-center", "p-2", "rounded-circle", "border-0", 3, "click"], [1, "bi", "bi-list", "fs-5", "text-dark"], ["routerLink", "/", 1, "navbar-brand", "d-flex", "align-items-center", "m-0"], ["src", "/BuildTrack_Logo.png", "alt", "BuildTrack Logo", 2, "height", "58px", "object-fit", "contain"], [1, "position-relative"], ["title", "Notifications", 1, "btn", "btn-light", "d-flex", "align-items-center", "justify-content-center", "p-2", "rounded-circle", "border-0", "position-relative", 3, "click"], [1, "bi", "bi-bell", "fs-5", "text-dark"], [1, "position-absolute", "top-0", "start-100", "translate-middle", "badge", "rounded-pill", "bg-danger", "border", "border-white"], [1, "dropdown-menu", "show", "position-absolute", "end-0", "mt-2", "shadow", "border-0", "rounded-3", "p-0", 2, "width", "320px", "z-index", "1050"], [1, "vr", "bg-secondary", "opacity-25", 2, "height", "24px"], [1, "btn", "btn-light", "p-1", "d-flex", "align-items-center", "gap-2", "border-0", "rounded-pill", "pe-3", 3, "click"], ["alt", "User profile", 1, "rounded-circle", "border", "border-2", "border-primary", 2, "width", "36px", "height", "36px", "object-fit", "cover", 3, "src"], [1, "d-none", "d-md-block", "text-start"], [1, "fw-bold", "text-dark", "lh-1", 2, "font-size", "13px"], [1, "text-muted", 2, "font-size", "11px"], [1, "bi", "bi-chevron-down", "text-muted", "small"], [1, "dropdown-menu", "show", "position-absolute", "end-0", "mt-2", "shadow", "border-0", "rounded-3", "p-1", 2, "width", "220px", "z-index", "1050"], [1, "px-3", "py-2", "border-bottom", "d-flex", "justify-content-between", "align-items-center", "bg-light", "rounded-top"], [1, "fw-bold", "text-dark"], [1, "btn", "btn-link", "btn-sm", "text-decoration-none", "p-0"], [1, "list-group", "list-group-flush", "max-height-300", "overflow-y-auto"], [1, "list-group-item", "list-group-item-action", "p-3", 3, "bg-light"], [1, "p-2", "border-top", "text-center", "bg-light", "rounded-bottom"], ["href", "#", 1, "small", "text-primary", "text-decoration-none", "fw-semibold"], [1, "btn", "btn-link", "btn-sm", "text-decoration-none", "p-0", 3, "click"], [1, "list-group-item", "list-group-item-action", "p-3"], [1, "mb-1", "small", "fw-medium"], [1, "text-muted", "d-block", "mt-1"], [1, "bi", "bi-clock", "me-1"], [1, "px-3", "py-2", "border-bottom", "mb-1"], [1, "text-muted"], ["routerLink", "/profile", 1, "dropdown-item", "rounded-2", "py-2", "d-flex", "align-items-center", "gap-2", "text-dark"], [1, "bi", "bi-person", "text-muted", "fs-5"], ["routerLink", "/settings", 1, "dropdown-item", "rounded-2", "py-2", "d-flex", "align-items-center", "gap-2", "text-dark"], [1, "bi", "bi-gear", "text-muted", "fs-5"], [1, "my-1", "border-light"], [1, "dropdown-item", "rounded-2", "py-2", "d-flex", "align-items-center", "gap-2", "text-danger", "fw-medium", 3, "click"], [1, "bi", "bi-box-arrow-right", "fs-5"]], template: function NavbarComponent_Template(rf, ctx) { if (rf & 1) {
            i0.ɵɵelementStart(0, "header", 0)(1, "div", 1)(2, "div", 2)(3, "button", 3);
            i0.ɵɵlistener("click", function NavbarComponent_Template_button_click_3_listener() { return ctx.toggleSidebar.emit(); });
            i0.ɵɵelement(4, "i", 4);
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(5, "a", 5);
            i0.ɵɵelement(6, "img", 6);
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(7, "div", 2)(8, "div", 7)(9, "button", 8);
            i0.ɵɵlistener("click", function NavbarComponent_Template_button_click_9_listener() { return ctx.toggleNotify(); });
            i0.ɵɵelement(10, "i", 9);
            i0.ɵɵconditionalCreate(11, NavbarComponent_Conditional_11_Template, 2, 1, "span", 10);
            i0.ɵɵelementEnd();
            i0.ɵɵconditionalCreate(12, NavbarComponent_Conditional_12_Template, 11, 1, "div", 11);
            i0.ɵɵelementEnd();
            i0.ɵɵelement(13, "div", 12);
            i0.ɵɵelementStart(14, "div", 7)(15, "button", 13);
            i0.ɵɵlistener("click", function NavbarComponent_Template_button_click_15_listener() { return ctx.toggleProfile(); });
            i0.ɵɵelement(16, "img", 14);
            i0.ɵɵelementStart(17, "div", 15)(18, "div", 16);
            i0.ɵɵtext(19);
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(20, "span", 17);
            i0.ɵɵtext(21);
            i0.ɵɵelementEnd()();
            i0.ɵɵelement(22, "i", 18);
            i0.ɵɵelementEnd();
            i0.ɵɵconditionalCreate(23, NavbarComponent_Conditional_23_Template, 16, 2, "div", 19);
            i0.ɵɵelementEnd()()()();
        } if (rf & 2) {
            let tmp_4_0;
            let tmp_5_0;
            i0.ɵɵadvance(9);
            i0.ɵɵclassProp("active", ctx.showNotifications);
            i0.ɵɵadvance(2);
            i0.ɵɵconditional(ctx.unreadCount > 0 ? 11 : -1);
            i0.ɵɵadvance();
            i0.ɵɵconditional(ctx.showNotifications ? 12 : -1);
            i0.ɵɵadvance(3);
            i0.ɵɵclassProp("active", ctx.showProfileMenu);
            i0.ɵɵadvance();
            i0.ɵɵproperty("src", ((tmp_4_0 = ctx.authService.currentUser()) == null ? null : tmp_4_0.avatar) || "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=100", i0.ɵɵsanitizeUrl);
            i0.ɵɵadvance(3);
            i0.ɵɵtextInterpolate((tmp_5_0 = ctx.authService.currentUser()) == null ? null : tmp_5_0.name);
            i0.ɵɵadvance(2);
            i0.ɵɵtextInterpolate(ctx.userRoleLabel);
            i0.ɵɵadvance(2);
            i0.ɵɵconditional(ctx.showProfileMenu ? 23 : -1);
        } }, dependencies: [CommonModule, RouterModule, i1.RouterLink], styles: [".navbar[_ngcontent-%COMP%] {\n  height: 70px;\n  z-index: 1040;\n}\n\n.btn-light[_ngcontent-%COMP%] {\n  background-color: #f8f9fa;\n  transition: all 0.2s ease-in-out;\n}\n\n.btn-light[_ngcontent-%COMP%]:hover, .btn-light.active[_ngcontent-%COMP%] {\n  background-color: #e9ecef;\n  transform: scale(1.05);\n}\n\n.max-height-300[_ngcontent-%COMP%] {\n  max-height: 300px;\n}\n\n.dropdown-menu[_ngcontent-%COMP%] {\n  animation: _ngcontent-%COMP%_dropdownFadeIn 0.2s cubic-bezier(0.16, 1, 0.3, 1);\n  display: block;\n}\n\n.dropdown-item[_ngcontent-%COMP%] {\n  transition: background-color 0.15s ease-in-out, color 0.15s ease-in-out;\n  font-size: 14px;\n}\n\n.dropdown-item[_ngcontent-%COMP%]:hover {\n  background-color: #f1f3f9;\n}\n\n@keyframes _ngcontent-%COMP%_dropdownFadeIn {\n  from {\n    opacity: 0;\n    transform: translateY(10px) scale(0.95);\n  }\n  to {\n    opacity: 1;\n    transform: translateY(0) scale(1);\n  }\n}"] });
}
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassMetadata(NavbarComponent, [{
        type: Component,
        args: [{ selector: 'app-navbar', standalone: true, imports: [CommonModule, RouterModule], template: "<header class=\"navbar navbar-expand-lg fixed-top shadow-sm px-4 bg-white border-bottom\">\n  <div class=\"container-fluid p-0 d-flex justify-content-between align-items-center\">\n    \n    <!-- Branding & Sidebar Toggle -->\n    <div class=\"d-flex align-items-center gap-3\">\n      <button class=\"btn btn-light d-flex align-items-center justify-content-center p-2 rounded-circle border-0\" \n              (click)=\"toggleSidebar.emit()\" \n              id=\"sidebarToggleBtn\"\n              title=\"Toggle Sidebar\">\n        <i class=\"bi bi-list fs-5 text-dark\"></i>\n      </button>\n      <a class=\"navbar-brand d-flex align-items-center m-0\" routerLink=\"/\">\n        <img src=\"/BuildTrack_Logo.png\" alt=\"BuildTrack Logo\" style=\"height: 58px; object-fit: contain;\">\n      </a>\n    </div>\n\n    <!-- Right Side Actions (Notifications & User Settings) -->\n    <div class=\"d-flex align-items-center gap-3\">\n      \n      <!-- Notifications Indicator -->\n      <div class=\"position-relative\">\n        <button class=\"btn btn-light d-flex align-items-center justify-content-center p-2 rounded-circle border-0 position-relative\" \n                (click)=\"toggleNotify()\" \n                [class.active]=\"showNotifications\"\n                title=\"Notifications\">\n          <i class=\"bi bi-bell fs-5 text-dark\"></i>\n          @if (unreadCount > 0) {\n            <span class=\"position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger border border-white\">\n              {{ unreadCount }}\n            </span>\n          }\n        </button>\n        \n        <!-- Notifications Dropdown Panel -->\n        @if (showNotifications) {\n          <div class=\"dropdown-menu show position-absolute end-0 mt-2 shadow border-0 rounded-3 p-0\" style=\"width: 320px; z-index: 1050;\">\n            <div class=\"px-3 py-2 border-bottom d-flex justify-content-between align-items-center bg-light rounded-top\">\n              <span class=\"fw-bold text-dark\">Notifications</span>\n              @if (unreadCount > 0) {\n                <button class=\"btn btn-link btn-sm text-decoration-none p-0\" (click)=\"markAllAsRead()\">Mark as read</button>\n              }\n            </div>\n            <div class=\"list-group list-group-flush max-height-300 overflow-y-auto\">\n              @for (n of notifications; track n.id) {\n                <div class=\"list-group-item list-group-item-action p-3\" [class.bg-light]=\"n.unread\">\n                  <p class=\"mb-1 small fw-medium\" [class.text-dark]=\"n.unread\" [class.text-muted]=\"!n.unread\">{{ n.text }}</p>\n                  <small class=\"text-muted d-block mt-1\"><i class=\"bi bi-clock me-1\"></i>{{ n.time }}</small>\n                </div>\n              }\n            </div>\n            <div class=\"p-2 border-top text-center bg-light rounded-bottom\">\n              <a href=\"#\" class=\"small text-primary text-decoration-none fw-semibold\">View All Notifications</a>\n            </div>\n          </div>\n        }\n      </div>\n\n      <!-- Vertical Divider -->\n      <div class=\"vr bg-secondary opacity-25\" style=\"height: 24px;\"></div>\n\n      <!-- User Profile Dropdown -->\n      <div class=\"position-relative\">\n        <button class=\"btn btn-light p-1 d-flex align-items-center gap-2 border-0 rounded-pill pe-3\" \n                (click)=\"toggleProfile()\"\n                [class.active]=\"showProfileMenu\">\n          <img [src]=\"authService.currentUser()?.avatar || 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=100'\" \n               alt=\"User profile\" \n               class=\"rounded-circle border border-2 border-primary\" \n               style=\"width: 36px; height: 36px; object-fit: cover;\">\n          <div class=\"d-none d-md-block text-start\">\n            <div class=\"fw-bold text-dark lh-1\" style=\"font-size: 13px;\">{{ authService.currentUser()?.name }}</div>\n            <span class=\"text-muted\" style=\"font-size: 11px;\">{{ userRoleLabel }}</span>\n          </div>\n          <i class=\"bi bi-chevron-down text-muted small\"></i>\n        </button>\n\n        <!-- Profile Menu Dropdown Panel -->\n        @if (showProfileMenu) {\n          <div class=\"dropdown-menu show position-absolute end-0 mt-2 shadow border-0 rounded-3 p-1\" style=\"width: 220px; z-index: 1050;\">\n            <div class=\"px-3 py-2 border-bottom mb-1\">\n              <div class=\"fw-bold text-dark\">{{ authService.currentUser()?.name }}</div>\n              <small class=\"text-muted\">{{ authService.currentUser()?.email }}</small>\n            </div>\n            <a class=\"dropdown-item rounded-2 py-2 d-flex align-items-center gap-2 text-dark\" routerLink=\"/profile\">\n              <i class=\"bi bi-person text-muted fs-5\"></i> My Profile\n            </a>\n            <a class=\"dropdown-item rounded-2 py-2 d-flex align-items-center gap-2 text-dark\" routerLink=\"/settings\">\n              <i class=\"bi bi-gear text-muted fs-5\"></i> Settings\n            </a>\n            <hr class=\"my-1 border-light\">\n            <button class=\"dropdown-item rounded-2 py-2 d-flex align-items-center gap-2 text-danger fw-medium\" (click)=\"logout()\">\n              <i class=\"bi bi-box-arrow-right fs-5\"></i> Logout\n            </button>\n          </div>\n        }\n      </div>\n\n    </div>\n  </div>\n</header>\n", styles: [".navbar {\n  height: 70px;\n  z-index: 1040;\n}\n\n.btn-light {\n  background-color: #f8f9fa;\n  transition: all 0.2s ease-in-out;\n}\n\n.btn-light:hover, .btn-light.active {\n  background-color: #e9ecef;\n  transform: scale(1.05);\n}\n\n.max-height-300 {\n  max-height: 300px;\n}\n\n.dropdown-menu {\n  animation: dropdownFadeIn 0.2s cubic-bezier(0.16, 1, 0.3, 1);\n  display: block;\n}\n\n.dropdown-item {\n  transition: background-color 0.15s ease-in-out, color 0.15s ease-in-out;\n  font-size: 14px;\n}\n\n.dropdown-item:hover {\n  background-color: #f1f3f9;\n}\n\n@keyframes dropdownFadeIn {\n  from {\n    opacity: 0;\n    transform: translateY(10px) scale(0.95);\n  }\n  to {\n    opacity: 1;\n    transform: translateY(0) scale(1);\n  }\n}\n"] }]
    }], null, { toggleSidebar: [{
            type: Output
        }] }); })();
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassDebugInfo(NavbarComponent, { className: "NavbarComponent", filePath: "src/app/components/navbar/navbar.ts", lineNumber: 13 }); })();
