import { Component, Output, EventEmitter, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './navbar.html',
  styleUrl: './navbar.css'
})
export class NavbarComponent {
  authService = inject(AuthService);
  
  @Output() toggleSidebar = new EventEmitter<void>();

  showNotifications = false;
  showProfileMenu = false;

  // Mock notifications list
  notifications = [
    { id: 1, text: 'New issue reported at Vanguard Heights: Leakage detected', time: '10m ago', unread: true },
    { id: 2, text: 'Cement material request approved for Vance Concrete', time: '1h ago', unread: true },
    { id: 3, text: 'Weekly progress report generated by Shradha S', time: '4h ago', unread: false }
  ];

  get unreadCount() {
    return this.notifications.filter(n => n.unread).length;
  }

  get userRoleLabel(): string {
    const role = this.authService.userRole();
    if (!role) return '';
    return role.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
  }

  toggleNotify() {
    this.showNotifications = !this.showNotifications;
    this.showProfileMenu = false;
  }

  toggleProfile() {
    this.showProfileMenu = !this.showProfileMenu;
    this.showNotifications = false;
  }

  markAllAsRead() {
    this.notifications.forEach(n => n.unread = false);
  }

  logout() {
    this.authService.logout();
  }
}
